### ISSUE TITLE
Add hooks

### ISSUE THREAD

**Issue by czan** [ferfebles/redtick#2]
I'd love to be able to hook in a custom function at the transition points of a pomodoro cycle (starting work, starting rest, finishing rest). Any chance we could get a hook (in the emacs sense of `add-hook`/`run-hooks`) for them?

The sound playing stuff could then be implemented on top of those hooks, while leaving things open for other functionality to be added in more easily.

**Comment by ferfebles** [comment]
Seems a good idea. I'm starting with elisp, but I'll try to implement the hooks.

Thanks for this suggestion.
